#!/usr/bin/env bash
# One-off generator: Phase-1 city home pages (city-localized clone of index.html).
# Pure bash (no python/node on this box). Run from repo root: bash scripts/gen_city_pages.sh
set -euo pipefail
cd "$(dirname "$0")/.."
OUT="src"

# city|slug|state|county|region|hook|civic|HOODS|ZIPS|LANDMARKS
# HOODS/LANDMARKS already formatted as natural lists; ZIPS comma-joined.
read -r -d '' ROWS <<'DATA' || true
Corona del Mar|corona-del-mar-phone-psychic|CA|Orange County, California|Newport Beach @AMP@ the Orange Coast|between the bluffs on PCH or up in Newport Coast|the Corona del Mar branch library on Marigold Avenue|the Village, Shore Cliffs, Cameo Shores, Irvine Terrace, Newport Coast, and Pelican Hill|92625, 92614|Corona del Mar State Beach, Little Corona, the Sherman Library @AMP@ Gardens, Pacific Coast Highway, and Big Corona
Dana Point|dana-point-phone-psychic|CA|Orange County, California|the South Orange Coast|down in the Lantern District or up by Monarch Beach|the Dana Point Community Center on Golden Lantern|the Lantern District, Monarch Beach, Capistrano Beach, the Headlands, and Niguel Shores|92629, 92624|Dana Point Harbor, Doheny State Beach, Salt Creek Beach, the Ocean Institute, and Pacific Coast Highway
Vacaville|vacaville-phone-psychic|CA|Solano County, California|Solano County, between Sacramento and the Bay|out in Browns Valley or off Alamo Drive|the Vacaville Public Library on Town Square Place|Browns Valley, North Village, Alamo, Cheyenne, Padan, and the Creekside area|95687, 95688, 95696|the Vacaville Premium Outlets, Lagoon Valley Park, Andrews Park, the old Nut Tree, and Travis Air Force Base nearby
Pismo Beach|pismo-beach-phone-psychic|CA|San Luis Obispo County, California|the Five Cities on the Central Coast|up in Shell Beach or down by the pier|the Pismo Beach City Hall on Pomeroy Avenue|Shell Beach, Sunset Palisades, the Pier area, Pismo Heights, and the Mesa|93449|the Pismo Pier, the Monarch Butterfly Grove, Dinosaur Caves Park, the Pismo Beach Premium Outlets, and the Oceano Dunes
Interlaken|interlaken-phone-psychic|CA|Santa Cruz County, California|the Pajaro Valley near Watsonville|out by Pinto Lake or along Green Valley Road|the Pinto Lake County Park entrance on Green Valley Road|the Pinto Lake area, Wheelock, Amesti, Green Valley, and Buena Vista|95076|Pinto Lake, the Pajaro Valley farmland, the Watsonville Slough, Highway 152, and Mount Madonna nearby
Lakeport|lakeport-phone-psychic|CA|Lake County, California|the Clear Lake basin|along the lakefront or up in Lakeside Heights|the Lake County Courthouse on Main Street|downtown Lakeport, the lakefront, Lakeside Heights, Scotts Valley, and Finley|95453|Clear Lake, Library Park, the Lake County Courthouse Museum, Mount Konocti views, and Clear Lake State Park nearby
Rowland Heights|rowland-heights-phone-psychic|CA|Los Angeles County, California|the eastern San Gabriel Valley|up by Powder Canyon or along Colima Road|the Rowland Heights Community Center on Nogales Street|Pathfinder, Nogales, the Colima corridor, Powder Canyon, and Vantage Pointe|91748, 91745|Schabarum Regional Park, the Puente Hills, the Pomona (60) Freeway, Powder Canyon trails, and the Colima Road shops
Palmdale|palmdale-phone-psychic|CA|Los Angeles County, California|the Antelope Valley|out in Rancho Vista or up toward Anaverde|Palmdale City Hall on East Avenue Q|Rancho Vista, Anaverde, the Quartz Hill side, the Courson area, and Desert View Highlands|93550, 93551, 93552, 93591|the Antelope Valley poppy fields, the Palmdale Amphitheater, DryTown Water Park, Marie Kerr Park, and the Antelope Valley (14) Freeway
Solvang|solvang-phone-psychic|CA|Santa Barbara County, California|the Santa Ynez Valley|near the mission or out toward the Alisal|Solvang City Hall on First Street|the Danish village center, Alisal, Skytt Mesa, and the Atterdag area|93463|the Old Mission Santa Inés, the Solvang windmills, Hans Christian Andersen Park, Santa Ynez Valley wine country, and Highway 246
Placerville|placerville-phone-psychic|CA|El Dorado County, California|the Sierra foothills Gold Country|up Cedar Ravine or out toward Smith Flat|the El Dorado County Historical Museum on Placerville Drive|historic Main Street, the Hangtown area, Smith Flat, the Gold Hill side, and Cedar Ravine|95667|historic Main Street, Gold Bug Park @AMP@ Mine, Apple Hill nearby, the Highway 50 corridor toward Tahoe, and the El Dorado County fairgrounds
Koreatown|koreatown-phone-psychic|CA|Los Angeles, California|central Los Angeles|off Wilshire or near the Wiltern|the Pio Pico Koreatown branch library on Grand View Street|Wilshire Center, the Wiltern area, Country Club Park, the Harvard Heights edge, and the Vermont corridor|90004, 90005, 90006, 90010, 90020|the Wiltern Theatre, Lafayette Park, the Wilshire/Western Metro station, Wilshire Boulevard, and the Robert F. Kennedy Community Schools
Healdsburg|healdsburg-phone-psychic|CA|Sonoma County, California|Sonoma wine country|near the Plaza or out toward Dry Creek|Healdsburg City Hall on Grant Street|the Plaza, Fitch Mountain, the Dry Creek side, the Alexander Valley edge, and Parkland Farms|95448|the Healdsburg Plaza, the Russian River, Dry Creek Valley vineyards, Fitch Mountain, and Alexander Valley
Ukiah|ukiah-phone-psychic|CA|Mendocino County, California|inland Mendocino County|on the Westside or out by Vichy Springs|the Mendocino County Courthouse on West Perkins Street|downtown Ukiah, the Westside, Yokayo, the Vichy Springs area, and Deerwood|95482|the Grace Hudson Museum, Lake Mendocino, Low Gap Park, the Mendocino County Courthouse, and the Highway 101 corridor
Cerritos|cerritos-phone-psychic|CA|Los Angeles County, California|the Gateway Cities|near the Towne Center or off Bloomfield|Cerritos City Hall on Bloomfield Avenue|Cerritos Towne Center, the College Park area, Sunny Cove, and the Bloomfield corridor|90703|the Cerritos Center for the Performing Arts, Los Cerritos Center, Cerritos Regional Park, the 605 and 91 freeways, and the Cerritos Sculpture Garden
Cambria|cambria-phone-psychic|CA|San Luis Obispo County, California|the Central Coast near San Simeon|up on Lodge Hill or down by Moonstone Beach|the Cambria Veterans Memorial Building on Main Street|the East Village, the West Village, Marine Terrace, Lodge Hill, and Park Hill|93428|Moonstone Beach, the Fiscalini Ranch Preserve, Hearst Castle near San Simeon, Highway 1, and the Piedras Blancas elephant seals
Rancho Cordova|rancho-cordova-phone-psychic|CA|Sacramento County, California|greater Sacramento|out in Anatolia or near Old Town|Rancho Cordova City Hall on Civic Center Drive|Mills, Anatolia, Sunrise Douglas, the Old Town, and the Rancho Murieta side|95670, 95742, 95741|the American River, Hagan Community Park, the Highway 50 corridor, Mather Airport, and Folsom Lake nearby
Glendale|glendale-phone-psychic|CA|Los Angeles County, California|the foot of the Verdugo Mountains|down Brand Boulevard or up Glenoaks|Glendale City Hall on East Broadway|Adams Hill, Glenoaks Canyon, Verdugo Woodlands, Sparr Heights, Riverside Rancho, Northwest Glendale, and the Glendale Galleria area|91201, 91202, 91203, 91204, 91205, 91206, 91207, 91208, 91214|the Glendale Galleria, the Americana at Brand, Forest Lawn Memorial-Park, Brand Park, Verdugo Park, and the 134 and 2 freeways
Pasadena|pasadena-phone-psychic|CA|Los Angeles County, California|the San Gabriel Valley foothills|in Old Pasadena or up by the Rose Bowl|Pasadena City Hall on East Walnut Street|Old Pasadena, Bungalow Heaven, Madison Heights, South Lake, Linda Vista, San Rafael, and Hastings Ranch|91101, 91103, 91104, 91105, 91106, 91107, 91108|the Rose Bowl, Old Pasadena, the Norton Simon Museum, Caltech, Colorado Boulevard, and the 210 and 134 freeways
North Hollywood|north-hollywood-phone-psychic|CA|Los Angeles, California|the southeast San Fernando Valley|in the NoHo Arts District or along Lankershim|the North Hollywood Library on Tujunga Avenue|the NoHo Arts District, Toluca Woods, the Valley Village edge, Studio Village, and Magnolia Woods|91601, 91602, 91605, 91606|the NoHo Arts District, Universal Studios nearby, Lankershim Boulevard, the Red Line at NoHo station, and the 170 and 134 freeways
Studio City|studio-city-phone-psychic|CA|Los Angeles, California|the southern San Fernando Valley|along Ventura Boulevard or up Laurel Canyon|the Studio City Branch Library on Vineland Avenue|Colfax Meadows, the Silver Triangle, Carpenter, Laurel Terrace, and the Ventura Boulevard corridor|91604|CBS Studio Center, the Ventura Boulevard restaurants, Fryman Canyon, Laurel Canyon, and the 101 and 134 freeways
Toluca Lake|toluca-lake-phone-psychic|CA|Los Angeles, California|the south edge of Burbank|by the lake or along Riverside Drive|the Toluca Lake Community Center|the lake area, Toluca Woods, and the Riverside Drive corridor|91602|Toluca Lake itself, Lakeside Golf Club, Riverside Drive, the Warner Bros. backlot edge, and the 134 freeway
Sherman Oaks|sherman-oaks-phone-psychic|CA|Los Angeles, California|the south-central San Fernando Valley|off Ventura or up in Royal Oaks|the Sherman Oaks Branch Library on Moorpark Street|Chandler Estates, Royal Oaks, the Ventura corridor, and Longridge Estates|91403, 91413, 91423|the Sherman Oaks Galleria, Ventura Boulevard, Sepulveda Boulevard, the 101 and 405 freeways, and Lake Balboa nearby
La Cañada Flintridge|la-canada-flintridge-phone-psychic|CA|Los Angeles County, California|the foothills above Pasadena|along Foothill or up near Descanso|La Cañada Flintridge City Hall on Foothill Boulevard|La Cañada, Flintridge, the Foothill Boulevard corridor, and Sagebrush|91011, 91012|Descanso Gardens, the Jet Propulsion Laboratory nearby, the 210 Foothill Freeway, and the Crescenta Valley
Sun Valley|sun-valley-phone-psychic|CA|Los Angeles, California|the northeast San Fernando Valley|out near Hansen Dam or along Sunland Boulevard|the Sun Valley Branch Library on Vineland Avenue|Stonehurst, the Pendleton Park area, the Sunland edge, and the Burbank Boulevard corridor|91352|Hansen Dam Recreation Area, Stonehurst Park, the 5 and 170 freeways, Hollywood Burbank Airport nearby, and Sun Valley Park
Hollywood|hollywood-phone-psychic|CA|Los Angeles, California|central Los Angeles|off the Hollywood Walk of Fame or up in the Hills|the Hollywood and Highland complex on Hollywood Boulevard|the Hollywood Hills, Franklin Village, Beachwood Canyon, Thai Town, and Little Armenia|90028, 90038, 90068|the Hollywood Sign, the Hollywood Walk of Fame, the TCL Chinese Theatre, Hollywood Boulevard, Sunset Boulevard, and Griffith Observatory nearby
West Hollywood|west-hollywood-phone-psychic|CA|Los Angeles County, California|the LA Westside fringe|on the Sunset Strip or off Santa Monica|West Hollywood City Hall on North San Vicente Boulevard|the Sunset Strip, Boys Town, the Norma Triangle, and the Eastside|90046, 90048, 90069|the Sunset Strip, the Whisky a Go Go, the Pacific Design Center, Melrose Avenue, and Santa Monica Boulevard
Universal City|universal-city-phone-psychic|CA|Los Angeles County, California|the south edge of Burbank by Universal Studios|by CityWalk or up on the lot|the Universal CityWalk main entrance|the studios district and the Cahuenga Pass approach|91608|Universal Studios Hollywood, CityWalk, the 101 Hollywood Freeway, and Lankershim Boulevard
Valley Village|valley-village-phone-psychic|CA|Los Angeles, California|the south-central San Fernando Valley|off Magnolia or by Valley Village Park|the Valley Village Park on Whitsett Avenue|the Magnolia Park area, Laurel Plaza, and the Colfax Meadows edge|91607|Magnolia Boulevard, Laurel Hall, the 170 Hollywood Freeway, and Burbank Boulevard
Van Nuys|van-nuys-phone-psychic|CA|Los Angeles, California|the central San Fernando Valley|along Van Nuys Boulevard or near the airport|Van Nuys City Hall on Sylvan Street|the Van Nuys Boulevard corridor, Tobias-Cedros, the Lake Balboa edge, and Kester Ridge|91401, 91405, 91406, 91411|Van Nuys Boulevard, Van Nuys Airport, Sherman Way, the 405 San Diego Freeway, and the Sepulveda Basin
Encino|encino-phone-psychic|CA|Los Angeles, California|the south-central San Fernando Valley|off Ventura or up in the hills|the Encino Branch Library on Ventura Boulevard|Royal Hills, the Vista de Oro area, the Encino Hills, and Encino Village|91316, 91436|Ventura Boulevard, the Encino Reservoir, Encino Park, and the Sepulveda Basin Recreation Area
Silver Lake|silver-lake-phone-psychic|CA|Los Angeles, California|the LA eastside|by the Reservoir or up at Sunset Junction|the Silver Lake Branch Library on Glendale Boulevard|Sunset Junction, the Reservoir district, Ivanhoe, and Moreno Highlands|90026, 90039|the Silver Lake Reservoir, Sunset Junction, Sunset Boulevard, and Echo Park Lake nearby
Los Feliz|los-feliz-phone-psychic|CA|Los Angeles, California|the LA eastside foothills|along Vermont or up by Griffith Park|the John C. Fremont Branch Library on Hollywood Boulevard|Franklin Hills, Los Feliz Heights, the Vermont corridor, and the Hillhurst Avenue area|90027, 90039|Griffith Park, the Griffith Observatory, the Greek Theatre, Vermont Avenue, and Hollywood Boulevard
DATA

TPL="$(cat scripts/city.tpl)"

count=0
while IFS='|' read -r CITY SLUG STATE COUNTY REGION HOOK CIVIC HOODS ZIPS LANDMARKS; do
  [ -z "${CITY:-}" ] && continue
  CITY_L="$(echo "$CITY" | tr '[:upper:]' '[:lower:]')"
  STATE_L="$(echo "$STATE" | tr '[:upper:]' '[:lower:]')"
  page="$TPL"
  page="${page//\{\{SLUG\}\}/$SLUG}"
  page="${page//\{\{CITY_L\}\}/$CITY_L}"
  page="${page//\{\{STATE_L\}\}/$STATE_L}"
  page="${page//\{\{CITY\}\}/$CITY}"
  page="${page//\{\{STATE\}\}/$STATE}"
  page="${page//\{\{COUNTY\}\}/$COUNTY}"
  page="${page//\{\{REGION\}\}/$REGION}"
  page="${page//\{\{HOOK\}\}/$HOOK}"
  page="${page//\{\{CIVIC\}\}/$CIVIC}"
  page="${page//\{\{HOODS\}\}/$HOODS}"
  page="${page//\{\{ZIPS\}\}/$ZIPS}"
  page="${page//\{\{LANDMARKS\}\}/$LANDMARKS}"
  printf '%s' "$page" > "$OUT/$SLUG.html"
  sed -i 's/@AMP@/\&amp;/g' "$OUT/$SLUG.html"
  echo "wrote $SLUG.html"
  count=$((count+1))
done <<< "$ROWS"
echo "done $count pages"
