# Build-time image optimizer.
# For every <img src="assets/img/X.jpg" ...>:
#   - Wrap in <picture> with WebP source so modern browsers fetch the
#     ~50-70%-smaller .webp variant (generated by scripts/gen_webp.sh)
#     while older browsers fall back to the original JPG.
#   - Add decoding="async" so image decoding doesn't block the main thread.
#   - Add loading="lazy" unless the image is the hero (above the fold).
#   - Add fetchpriority="high" on the hero image so the browser prioritizes
#     it over other resources - directly targets Lighthouse LCP score.
#
# Hero detection: any <img> inside a <div class="hero-img"> ... </div>.
# That selector is unique to the hero template across the site.

BEGIN { in_hero = 0 }

/<div class="hero-img">/ { in_hero = 1 }
/<\/div>/ {
  if (in_hero) {
    # Print the closing div, then drop the hero flag
    print
    in_hero = 0
    next
  }
}

{
  line = $0
  # Only transform <img ... src="assets/img/X.jpg" ...> on a single line
  if (line ~ /<img[[:space:]][^>]*src="assets\/img\/[A-Za-z0-9_.-]+\.jpg"/) {
    # Extract src
    if (match(line, /src="assets\/img\/[A-Za-z0-9_.-]+\.jpg"/)) {
      src_attr = substr(line, RSTART, RLENGTH)         # e.g. src="assets/img/foo.jpg"
      src_val  = substr(src_attr, 6, length(src_attr) - 6)  # strip src=" and "
      webp_val = src_val
      sub(/\.jpg$/, ".webp", webp_val)

      is_hero = in_hero

      # Add fetchpriority="high" on hero (if not already present)
      if (is_hero && line !~ /fetchpriority=/) {
        sub(/<img /, "<img fetchpriority=\"high\" ", line)
      }
      # Add loading="lazy" on non-hero (if not already present)
      if (!is_hero && line !~ /loading=/) {
        sub(/<img /, "<img loading=\"lazy\" ", line)
      }
      # Add decoding="async" if not already present
      if (line !~ /decoding=/) {
        sub(/<img /, "<img decoding=\"async\" ", line)
      }

      # Wrap with <picture> + WebP source (browsers without WebP fall back to img)
      printf "<picture><source srcset=\"%s\" type=\"image/webp\">%s</picture>\n", webp_val, line
      next
    }
  }
  print
}
